export const Settings = {
    debug: false,

    width: 960,
    height: 640,

    playerSpeedX: 300,
    playerSpeedY: 300,

    playerBulletSpeedX: 800,
    enemyBulletSpeedX: 2,
    enemyShootFrequency: 1,
    enemyBulletPoolSize: 1000,

    enemyWidth: 50,
    enemyHeight: 50,

    waveEasyTimeMin: 4,
    waveEasyTimeMax: 8,
    waveEasyAmplitudeMin: 10,
    waveEasyAmplitudeMax: 50,
    waveEasyFrequencyMin: 0.1,
    waveEasyFrequencyMax: 0.25,
    waveEasyRxMin: 100,
    waveEasyRxMax: 200,
    waveEasyRyMin: 100,
    waveEasyRyMax: 200,
    waveEasySyMin: 0,
    waveEasySyMax: 640 - 50,

    waveMediumTimeMin: 4,
    waveMediumTimeMax: 8,
    waveMediumAmplitudeMin: 10,
    waveMediumAmplitudeMax: 50,
    waveMediumFrequencyMin: 0.1,
    waveMediumFrequencyMax: 0.25,
    waveMediumRxMin: 100,
    waveMediumRxMax: 200,
    waveMediumRyMin: 100,
    waveMediumRyMax: 200,
    waveMediumSyMin: 0,
    waveMediumSyMax: 640 - 50,

    waveHardTimeMin: 4,
    waveHardTimeMax: 8,
    waveHardAmplitudeMin: 10,
    waveHardAmplitudeMax: 50,
    waveHardFrequencyMin: 0.1,
    waveHardFrequencyMax: 0.25,
    waveHardRxMin: 100,
    waveHardRxMax: 200,
    waveHardRyMin: 100,
    waveHardRyMax: 200,
    waveHardSyMin: 0,
    waveHardSyMax: 640 - 50,

    engineTimeResolution: 1,

    epsilon: 0.1,
    delta: 1 / 1000,
};
